Repository nextcloud/photos, pull requests merged in 2019-12, with the labels that each got.

#13 Maps navigation entry
  lib/Controller/PageController.php
  src/router/index.js
  src/services/IsMapsInstalled.js
Labels: 2. developing, enhancement

#11 Add sidebar button on the Navigation
  js/photos.js
  js/photos.js.map
  lib/Controller/PageController.php
  src/components/Navigation.vue
  src/main.js
  src/mixins/FileFolder.scss
  src/router/index.js
  src/views/Albums.vue
  src/views/Tags.vue
Labels: 3. to review, enhancement

#24 Better grid sizes with navigation
  src/assets/grid-sizes.js
Labels: 3. to review, bug, design

#29 Show navigation on empty folder too
  js/photos.js
  js/photos.js.map
  src/components/EmptyContent.vue
  src/views/Albums.vue
  src/views/Tags.vue
  src/views/Timeline.vue
Labels: 3. to review, bug, feature: albums, feature: tags

#37 Remove undeeded scripts
  lib/Controller/PageController.php
  src/main.js
Labels: 3. to review

#34 Update app icons and 'Your photos' icon
  css/icons.scss
  img/app.svg
  img/photos.svg
  img/yourphotos.svg
  src/Photos.vue
Labels: 3. to review, design, enhancement

#62 Enh/performances/scroller
  js/1.js
  js/1.js.map
  js/2.js
  js/2.js.map
  js/3.js
  js/3.js.map
  js/photos.js
  js/photos.js.map
  package-lock.json
  package.json
  src/components/File.vue
  src/components/VirtualGrid.vue
Labels: 3. to review, enhancement, performances

#68 Use cropped preview to avoid pixelated images
  js/photos.js
  js/photos.js.map
  src/components/File.vue
Labels: 3. to review, enhancement, performances

#71 (Bugfix) Reset Timeline before mount
  js/photos.js
  js/photos.js.map
  src/views/Timeline.vue
Labels: 3. to review, bug, feature: timeline

#76 (Refactor) Remove unused array to chunk
  js/photos.js
  js/photos.js.map
  src/utils/ArrayChunk.js
  src/views/Timeline.vue
Labels: 3. to review

#77 (Fix) Reduce size of folder title
  js/photos.js
  js/photos.js.map
  src/components/Folder.vue
  src/components/FolderTagPreview.vue
Labels: 3. to review, design, enhancement, papercut
