Repository nextcloud/photos, pull requests merged in 2020-02, with the labels that each got.

#116 added headers for your photos and favs
  js/photos.js
  js/photos.js.map
  src/router/index.js
  src/views/Timeline.vue
Labels: 3. to review, backport-request, bug

#173 Fix/actions
  .github/workflows/lint.yml
  .github/workflows/node.yml
Labels: backport-request

#172 [stable18] added headers for your photos and favs
  js/photos.js
  js/photos.js.map
  src/router/index.js
  src/views/Timeline.vue
Labels: 3. to review, enhancement

#175 [stable18] Fix url escaping
  js/photos.js
  js/photos.js.map
  src/components/FolderTagPreview.vue
  src/services/AlbumContent.js
  src/views/Albums.vue
Labels: 3. to review, bug, high

#180 Use actions from tutorial
  .github/workflows/lint.yml
  .github/workflows/node.yml
Labels: 3. to review, backport-request, enhancement

#186 Avoid passing an incomplete cancel token object to axios
  js/0.js
  js/0.js.map
  js/photos.js
  js/photos.js.map
  src/components/Folder.vue
  src/components/Tag.vue
  src/patchedRequest.js
  src/utils/CancelableRequest.js
  src/views/Tags.vue
  src/views/Timeline.vue
Labels: 3. to review, bug

#207 ignore unavailable storages while scanning for albums
  lib/Controller/AlbumsController.php
Labels: 3. to review, backport-request, bug

#212 Don't flatten out albums
  lib/Controller/AlbumsController.php
Labels: 3. to review
