Repository nextcloud/photos, pull requests merged in 2020-12, with the labels that each got.

#581 Make sure we have a string to localecompare to
  js/photos-main.js
  js/photos-main.js.map
  src/utils/fileUtils.js
Labels: 3. to review, backport-request, bug

#584 [stable19] Make sure we have a string to localecompare to
  .github/workflows/lint.yml
  .github/workflows/node.yml
  js/photos.0.js
  js/photos.0.js.map
  js/photos.1.js
  js/photos.1.js.map
  js/photos.2.js
  js/photos.2.js.map
  js/photos.4.js
  js/photos.4.js.map
  js/photos.5.js
  js/photos.5.js.map
  js/photos.6.js
  js/photos.6.js.map
  js/photos.7.js
  js/photos.7.js.map
  js/photos.8.js
  js/photos.8.js.map
  js/photos.9.js
  js/photos.9.js.map
  js/photos.js
  js/photos.js.map
  package-lock.json
  src/utils/fileUtils.js
Labels: 3. to review, bug

#585 [stable18] Make sure we have a string to localecompare to
  .github/workflows/lint.yml
  .github/workflows/node.yml
  babel.config.js
  js/photos-main.js
  js/photos-main.js.map
  js/photos.0.js
  js/photos.0.js.map
  js/photos.1.js
  js/photos.1.js.map
  js/photos.2.js
  js/photos.2.js.map
  js/photos.4.js
  js/photos.4.js.map
  js/photos.5.js
  js/photos.5.js.map
  js/photos.6.js
  js/photos.6.js.map
  js/photos.7.js
  js/photos.7.js.map
  js/photos.8.js
  js/photos.8.js.map
  js/photos.9.js
  js/photos.9.js.map
  js/photos.js
  js/photos.js.map
  package-lock.json
  package.json
  src/utils/fileUtils.js
Labels: 3. to review, bug

#610 Master is php7.3
  .github/workflows/lint.yml
  composer.json
Labels: 3. to review
