Repository nextcloud/photos, pull requests merged in 2020-07, with the labels that each got.

#389 Add php cs
  .github/workflows/lint.yml
  .gitignore
  .php_cs.dist
  appinfo/app.php
  composer.json
  composer.lock
  js/photos.1.js
  js/photos.1.js.map
  js/photos.4.js
  js/photos.4.js.map
  js/photos.5.js
  js/photos.5.js.map
  js/photos.6.js
  js/photos.6.js.map
  js/photos.js
  js/photos.js.map
  lib/AppInfo/Application.php
  lib/Controller/AlbumsController.php
  lib/Controller/PageController.php
  stylelint.config.js
Labels: 3. to review, backport-request, enhancement

#391 Use IBootstrap for the app
  appinfo/app.php
  lib/AppInfo/Application.php
Labels: 3. to review, technical debt

#398 Show groupfolders in shared folders
  lib/Controller/AlbumsController.php
Labels: 3. to review, backport-request, enhancement, integration, medium

#405 Fix IE11 compatibility
  js/photos.4.js
  js/photos.4.js.map
  js/photos.js
  js/photos.js.map
  package-lock.json
  package.json
  webpack.common.js
Labels: 3. to review, backport-request, bug

#408 Use `babel-loader-exclude-node-modules-except`
  js/photos-0.js
  js/photos-0.js.map
  js/photos-1.js
  js/photos-1.js.map
  js/photos-4.js
  js/photos-4.js.map
  js/photos-5.js
  js/photos-5.js.map
  js/photos-6.js
  js/photos-6.js.map
  js/photos-main.js
  js/photos-main.js.map
  package-lock.json
  package.json
  webpack.js
Labels: 3. to review, technical debt
