Repository nextcloud/photos, pull requests merged in 2020-01, with the labels that each got.

#78 (Bugfix) Resizing grid wasn't updating rows number
  js/photos.js
  js/photos.js.map
  src/components/VirtualGrid.vue
Labels: 3. to review, bug

#53 css for ellipsis
  js/photos.js
  js/photos.js.map
  src/components/Navigation.vue
Labels: 3. to review, bug, design

#91 Fix viewer list
  js/photos.js
  js/photos.js.map
  src/components/File.vue
  src/components/VirtualGrid.vue
  src/views/Albums.vue
  src/views/Tags.vue
Labels: 4. to release, bug, feature: albums, feature: tags, feature: timeline, high, integration

#99 Update viewer file list when cycling through
  js/photos.js
  js/photos.js.map
  src/components/File.vue
  src/views/Timeline.vue
Labels: 3. to review, enhancement, high

#100 Bump stable18
  js/1.js
  js/1.js.map
  js/2.js
  js/2.js.map
  js/3.js
  js/3.js.map
  js/photos.js
  js/photos.js.map
  package-lock.json
  package.json
  src/components/File.vue
  src/views/Timeline.vue
Labels: 3. to review

#112 Do not show preview if none available
  js/photos.js
  js/photos.js.map
  src/components/FolderTagPreview.vue
Labels: 3. to review, enhancement, feature: albums, feature: tags

#113 Fix shrinking of icons in long folder name
  js/photos.js
  js/photos.js.map
  src/components/Navigation.vue
Labels: 3. to review, bug, design

#66 readme and screenshot
  README.md
  screenshots/screenshot1.png
Labels: 3. to review

#117 fix map link
  lib/Controller/PageController.php
Labels: 4. to release, bug

#118 Remove warning messages when using svg in v-html
  js/photos.js
  js/photos.js.map
  src/Photos.vue
  src/components/EmptyContent.vue
Labels: 3. to review, low

#119 (Bugfix #115) Loading spinner position not centered
  js/photos.js
  js/photos.js.map
  src/Photos.vue
Labels: 3. to review, bug

#122 Fix url escaping
  js/photos.js
  js/photos.js.map
  src/components/FolderTagPreview.vue
  src/services/AlbumContent.js
  src/views/Albums.vue
Labels: 3. to review, bug, high

#123 Lint readme
  README.md
Labels: 3. to review

#124 Filter out unwanted tag mime
  js/photos.js
  js/photos.js.map
  src/services/TaggedImages.js
Labels: 3. to review, bug, feature: tags

#152 Lint with github actions
  .github/workflows/lint.yml
  composer.json
Labels: 3. to review, backport-request, enhancement

#157 No more drone. Do it all on github actions
  .drone.yml
  .github/workflows/nodejs.yml
Labels: 3. to review, backport-request

#159 Respect .noimage and .nomedia files
  lib/Controller/AlbumsController.php
Labels: 3. to review, backport-request, enhancement, feature: albums
