Repository nextcloud/photos, pull requests merged in 2020-10, with the labels that each got.

#278 Enable support for image/png
  lib/AppInfo/Application.php
Labels: 4. to release, discussion, enhancement

#468 Implement new Vue Virtual Grid
  js/photos-0.js
  js/photos-0.js.map
  js/photos-1.js
  js/photos-1.js.map
  js/photos-10.js
  js/photos-10.js.map
  js/photos-11.js
  js/photos-11.js.map
  js/photos-12.js
  js/photos-12.js.map
  js/photos-2.js
  js/photos-2.js.map
  js/photos-3.js
  js/photos-3.js.map
  js/photos-4.js
  js/photos-4.js.map
  js/photos-5.js
  js/photos-5.js.map
  js/photos-6.js
  js/photos-6.js.map
  js/photos-7.js
  js/photos-7.js.map
  js/photos-8.js
  js/photos-8.js.map
  js/photos-9.js
  js/photos-9.js.map
  js/photos-main.js
  js/photos-main.js.map
  package-lock.json
  package.json
  src/components/FileVirtualGrid.vue
  src/components/Navigation.vue
  src/components/SeparatorVirtualGrid.vue
  src/components/VirtualGrid.vue
  src/mixins/FileFolder.scss
  src/views/Albums.vue
  src/views/Tags.vue
  src/views/Timeline.vue
Labels: 4. to release, feature: timeline

#477 Implement "your videos" tab
  appinfo/routes.php
  js/photos-0.js
  js/photos-0.js.map
  js/photos-1.js
  js/photos-1.js.map
  js/photos-2.js
  js/photos-2.js.map
  js/photos-4.js
  js/photos-4.js.map
  js/photos-5.js
  js/photos-5.js.map
  js/photos-6.js
  js/photos-6.js.map
  js/photos-7.js
  js/photos-7.js.map
  js/photos-main.js
  js/photos-main.js.map
  lib/AppInfo/Application.php
  lib/Controller/AlbumsController.php
  lib/Controller/PageController.php
  src/Photos.vue
  src/router/index.js
  src/services/AllowedMimes.js
  src/services/PhotoSearch.js
  src/views/Timeline.vue
Labels: 3. to review, enhancement

#457 Rename "albums" to "folders"
  js/photos-main.js
  js/photos-main.js.map
  src/Photos.vue
  src/router/index.js
Labels: 4. to release, enhancement

#480 Fully migrate to the new Virtual Grid
  js/photos-0.js
  js/photos-0.js.map
  js/photos-1.js
  js/photos-1.js.map
  js/photos-10.js
  js/photos-10.js.map
  js/photos-11.js
  js/photos-11.js.map
  js/photos-12.js
  js/photos-12.js.map
  js/photos-13.js
  js/photos-13.js.map
  js/photos-2.js
  js/photos-2.js.map
  js/photos-3.js
  js/photos-3.js.map
  js/photos-4.js
  js/photos-4.js.map
  js/photos-5.js
  js/photos-5.js.map
  js/photos-6.js
  js/photos-6.js.map
  js/photos-7.js
  js/photos-7.js.map
  js/photos-8.js
  js/photos-8.js.map
  js/photos-9.js
  js/photos-9.js.map
  js/photos-main.js
  js/photos-main.js.map
  src/components/File.vue
  src/components/FileVirtualGrid.vue
  src/components/Folder.vue
  src/components/Grid.vue
  src/components/GridRow.vue
  src/components/Tag.vue
  src/views/Albums.vue
  src/views/Tags.vue
  src/views/Timeline.vue
Labels: 3. to review, enhancement

#487 Fix svg raw loading
  js/photos-0.js
  js/photos-0.js.map
  js/photos-1.js
  js/photos-1.js.map
  js/photos-10.js
  js/photos-10.js.map
  js/photos-2.js
  js/photos-2.js.map
  js/photos-4.js
  js/photos-4.js.map
  js/photos-5.js
  js/photos-5.js.map
  js/photos-6.js
  js/photos-6.js.map
  js/photos-7.js
  js/photos-7.js.map
  js/photos-8.js
  js/photos-8.js.map
  js/photos-9.js
  js/photos-9.js.map
  js/photos-main.js
  js/photos-main.js.map
  package-lock.json
  package.json
  webpack.js
Labels: 3. to review, bug, regression

#435 Non-cropped layout
  .eslintrc.js
  appinfo/routes.php
  js/photos-0.js
  js/photos-0.js.map
  js/photos-1.js
  js/photos-1.js.map
  js/photos-10.js
  js/photos-10.js.map
  js/photos-2.js
  js/photos-2.js.map
  js/photos-3.js
  js/photos-3.js.map
  js/photos-4.js
  js/photos-4.js.map
  js/photos-5.js
  js/photos-5.js.map
  js/photos-6.js
  js/photos-6.js.map
  js/photos-7.js
  js/photos-7.js.map
  js/photos-8.js
  js/photos-8.js.map
  js/photos-9.js
  js/photos-9.js.map
  js/photos-main.js
  js/photos-main.js.map
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/Photos.vue
  src/components/File.vue
  src/components/Settings/CroppedLayoutSettings.vue
  src/mixins/GridConfig.js
  src/mixins/UserConfig.js
  webpack.js
Labels: 3. to review, design, enhancement

#500 Fix wording squared photo view
  js/photos-main.js
  js/photos-main.js.map
  src/components/Settings/CroppedLayoutSettings.vue
Labels: 3. to review, papercut

#506 Rename view setting
  js/photos-main.js
  js/photos-main.js.map
  src/components/Settings/CroppedLayoutSettings.vue
Labels: 3. to review, papercut

#495 Rename shared with you tab
  js/photos-main.js
  js/photos-main.js.map
  src/Photos.vue
  src/router/index.js
Labels: 3. to review, bug

#509 Pass preview availability too
  lib/Controller/AlbumsController.php
Labels: 3. to review, backport-request, bug

#488 Instant feel
  appinfo/routes.php
  js/photos-0.js
  js/photos-0.js.map
  js/photos-11.js
  js/photos-11.js.map
  js/photos-12.js
  js/photos-12.js.map
  js/photos-13.js
  js/photos-13.js.map
  js/photos-2.js
  js/photos-2.js.map
  js/photos-3.js
  js/photos-3.js.map
  js/photos-5.js
  js/photos-5.js.map
  js/photos-6.js
  js/photos-6.js.map
  js/photos-7.js
  js/photos-7.js.map
  js/photos-main.js
  js/photos-main.js.map
  js/photos-service-worker.js
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  package-lock.json
  package.json
  src/Photos.vue
  src/components/File.vue
  webpack.js
Labels: 3. to review, enhancement

#513 hasPreview was undefined
  js/photos-0.js
  js/photos-0.js.map
  js/photos-main.js
  js/photos-main.js.map
  src/components/File.vue
Labels: 3. to review, papercut

#520 Bugfix wrong last date check
  js/photos-5.js
  js/photos-5.js.map
  js/photos-main.js
  js/photos-main.js.map
  src/views/Timeline.vue
Labels: 3. to review, bug

#514 Fix %2F bug in folder paths
  js/photos-6.js
  js/photos-6.js.map
  js/photos-7.js
  js/photos-7.js.map
  js/photos-main.js
  js/photos-main.js.map
  src/components/FolderTagPreview.vue
  src/router/index.js
Labels: 3. to review, bug

#503 show if tags are installed
  js/photos-2.js
  js/photos-2.js.map
  js/photos-3.js
  js/photos-main.js
  js/photos-main.js.map
  lib/Controller/PageController.php
  src/Photos.vue
  src/router/index.js
  src/services/AreTagsInstalled.js
Labels: 3. to review, bug

#507 Add recursive folder previews
  js/photos-0.js
  js/photos-0.js.map
  js/photos-7.js
  js/photos-7.js.map
  js/photos-main.js
  js/photos-main.js.map
  src/components/File.vue
  src/components/Folder.vue
  src/views/Albums.vue
Labels: 4. to release, bug

#521 Fix regression on timeline route
  js/photos-main.js
  js/photos-main.js.map
  src/Photos.vue
Labels: 3. to review, regression
