Repository nextcloud/photos, pull requests merged in 2021-08, with the labels that each got.

#842 Fix illustrations
  js/photos-0.js
  js/photos-0.js.map
  js/photos-1.js
  js/photos-1.js.map
  js/photos-10.js
  js/photos-10.js.map
  js/photos-2.js
  js/photos-2.js.map
  js/photos-3.js
  js/photos-3.js.map
  js/photos-4.js
  js/photos-4.js.map
  js/photos-5.js
  js/photos-5.js.map
  js/photos-6.js
  js/photos-6.js.map
  js/photos-7.js
  js/photos-7.js.map
  js/photos-8.js
  js/photos-8.js.map
  js/photos-9.js
  js/photos-9.js.map
  js/photos-main.js
  js/photos-main.js.map
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_empty_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_empty_svg.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_folder_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_folder_svg.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_images_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_images_svg.js.map
  js/photos-src_assets_Illustrations_empty_svg.js
  js/photos-src_assets_Illustrations_empty_svg.js.map
  js/photos-src_assets_Illustrations_folder_svg.js
  js/photos-src_assets_Illustrations_folder_svg.js.map
  js/photos-src_assets_Illustrations_images_svg.js
  js/photos-src_assets_Illustrations_images_svg.js.map
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js.map
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  package-lock.json
  src/components/EmptyContent.vue
  src/components/Navigation.vue
  webpack.js
Labels: 3. to review

#843 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#874 Update dependabot
  .github/workflows/dependabot-approve-merge.yml
Labels: 4. to release
