Repository nextcloud/photos, pull requests merged in 2022-01, with the labels that each got.

#945 Fix Timeline state management between routes
  js/photos-main.js
  js/photos-main.js.LICENSE.txt
  js/photos-main.js.map
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_empty_svg.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_folder_svg.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_images_svg.js.map
  src/Photos.vue
  src/store/files.js
  src/store/index.js
  src/views/Timeline.vue
Labels: bug, 3. to review

#950 Fix default previews
  js/photos-main.js
  js/photos-main.js.map
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_empty_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_folder_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_images_svg.js
  js/photos-src_assets_Illustrations_empty_svg.js
  js/photos-src_assets_Illustrations_empty_svg.js.map
  js/photos-src_assets_Illustrations_folder_svg.js
  js/photos-src_assets_Illustrations_folder_svg.js.map
  js/photos-src_assets_Illustrations_images_svg.js
  js/photos-src_assets_Illustrations_images_svg.js.map
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js.map
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  src/components/EmptyContent.vue
  src/components/File.vue
  webpack.js
Labels: bug, 3. to review

#952 [stable22] Fix default previews
  js/photos-main.js
  js/photos-main.js.map
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_empty_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_empty_svg.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_folder_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_folder_svg.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_images_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_images_svg.js.map
  js/photos-src_assets_Illustrations_empty_svg.js
  js/photos-src_assets_Illustrations_empty_svg.js.map
  js/photos-src_assets_Illustrations_folder_svg.js
  js/photos-src_assets_Illustrations_folder_svg.js.map
  js/photos-src_assets_Illustrations_images_svg.js
  js/photos-src_assets_Illustrations_images_svg.js.map
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js.map
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  src/components/EmptyContent.vue
  src/components/File.vue
  webpack.js
Labels: bug, 3. to review

#951 [stable23] Fix default previews
  js/photos-main.js
  js/photos-main.js.map
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_empty_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_empty_svg.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_folder_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_folder_svg.js.map
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_images_svg.js
  js/photos-node_modules_raw-loader_dist_cjs_js_src_assets_Illustrations_images_svg.js.map
  js/photos-src_assets_Illustrations_empty_svg.js
  js/photos-src_assets_Illustrations_empty_svg.js.map
  js/photos-src_assets_Illustrations_folder_svg.js
  js/photos-src_assets_Illustrations_folder_svg.js.map
  js/photos-src_assets_Illustrations_images_svg.js
  js/photos-src_assets_Illustrations_images_svg.js.map
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js.map
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  src/components/EmptyContent.vue
  src/components/File.vue
  webpack.js
Labels: bug, 3. to review

#947 Bump deps and audit fix
  js/photos-main.js
  js/photos-main.js.LICENSE.txt
  js/photos-main.js.map
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js.map
  js/photos-service-worker.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js.map
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  js/photos-vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-701342.js
  js/photos-vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-701342.js.map
  js/photos-vendors-node_modules_webdav_dist_node_index_js-node_modules_webdav_dist_node_request_js.js
  js/photos-vendors-node_modules_webdav_dist_node_index_js-node_modules_webdav_dist_node_request_js.js.map
  package-lock.json
  package.json
  src/assets/grid-sizes.js
  src/components/File.vue
  src/components/Folder.vue
  src/components/FolderTagPreview.vue
  src/components/Navigation.vue
  src/mixins/GridSizes.scss
  src/utils/SassGridConfig.js
  src/views/Albums.vue
  src/views/Tags.vue
  src/views/Timeline.vue
Labels: dependencies, security, 4. to release

#937 Implement 'On this day'
  appinfo/routes.php
  js/photos-main.js
  js/photos-main.js.map
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js.LICENSE.txt
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js.map
  src/Photos.vue
  src/components/SeparatorVirtualGrid.vue
  src/router/index.js
  src/services/PhotoSearch.js
  src/store/systemtags.js
  src/views/Timeline.vue
Labels: enhancement, 4. to release

#946 Fix Tags: Don't display tags without photos
  js/photos-main.js
  js/photos-main.js.map
  src/store/systemtags.js
Labels: bug, 3. to review

#980 Update workflows
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
Labels: enhancement, 3. to review, backport-request

#998 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: 3. to review, backport-request

#1017 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#1016 Npm audit fix
  js/photos-main.js
  js/photos-main.js.map
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js
  js/photos-node_modules_nextcloud_moment_node_modules_moment_locale_sync_recursive_-src_patchedRequest_j-3cb869.js.map
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js.map
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  package-lock.json
  src/Photos.vue
  src/components/File.vue
  src/components/Folder.vue
  src/components/FolderTagPreview.vue
  src/components/Navigation.vue
  src/components/Settings/CroppedLayoutSettings.vue
  src/components/Tag.vue
  src/views/Albums.vue
  src/views/Tags.vue
  src/views/Timeline.vue
Labels: enhancement, 3. to review, security
