Repository nextcloud/photos, pull requests merged in 2022-09, with the labels that each got.

#1216 Revert "[stable23] fix service-worker"
  js/photos-main.js
  js/photos-main.js.map
  src/Photos.vue
Labels: 3. to review

#1217 Revert "[stable24] fix service-worker"
  js/photos-main.js
  js/photos-main.js.map
  src/Photos.vue
Labels: 3. to review

#1221 Revert "Revert "[stable23] fix service-worker""
  js/photos-main.js
  js/photos-main.js.map
  src/Photos.vue
Labels: bug, 3. to review

#1220 Revert "Revert "[stable24] fix service-worker""
  js/photos-main.js
  js/photos-main.js.map
  src/Photos.vue
Labels: bug, 3. to review

#1228 Handle node deletion event
  lib/Album/AlbumMapper.php
  lib/AppInfo/Application.php
  lib/Event/MoveToTrashListener.php
  lib/Sabre/Album/PropFindPlugin.php
Labels: bug, 3. to review, high

#1244 Raise version to trigger migrations
  appinfo/info.xml
Labels: 3. to review

#1246 Add id to cypress config
  cypress.config.js
Labels: bug, 3. to review

#1261 Make photos_albums_files.owner nullable for beta migrations
  lib/Migration/Version20001Date20220830131446.php
Labels: 3. to review

#1262 owner really must allow null
  lib/Migration/Version20001Date20220830131446.php
Labels: bug, 3. to review

#1264 Fix public link button style
  src/components/Albums/CollaboratorsSelectionForm.vue
Labels: bug, 4. to release

#1265 Disambiguate `album_id` on group by
  lib/Album/AlbumMapper.php
Labels: bug, 3. to review

#1247 Polish albums - second round
  cypress/e2e/albums.cy.js
  cypress/e2e/shared_albums.cy.js
  cypress/support/commands.js
  lib/Album/AlbumMapper.php
  src/components/Albums/CollaboratorsSelectionForm.vue
  src/views/AlbumContent.vue
  src/views/Albums.vue
  src/views/SharedAlbumContent.vue
  src/views/SharedAlbums.vue
Labels: 2. developing, feature: albums

#1266 Add filename in temp album object during creation
  src/components/Albums/AlbumForm.vue
Labels: bug, 3. to review

#1268 Allow album owner to get file added by collaborators
  lib/Album/AlbumMapper.php
  lib/Controller/PreviewController.php
Labels: 3. to review

#1269 Fix download action
  src/components/Actions/ActionDownload.vue
Labels: bug, 3. to review

#1270 Disable downloading files from albums as it it not supported yet
  cypress/e2e/shared_albums.cy.js
  src/views/SharedAlbumContent.vue
Labels: bug, 3. to review

#1267 Make sure we have a valid source for each file
  src/components/File.vue
  src/components/FileLegacy.vue
  src/services/DavClient.js
  src/services/PhotoSearch.js
  src/utils/fileUtils.js
  src/views/AlbumContent.vue
  src/views/SharedAlbumContent.vue
Labels: bug, 3. to review

#1272 Fix collaborators avatar
  src/components/Albums/CollaboratorsSelectionForm.vue
Labels: 3. to review

#1274 Use HeaderNavigation to have sticky header
  src/router/index.js
  src/views/Timeline.vue
Labels: bug, 3. to review

#1276 Make failed file preview link take the full parent size
  src/components/File.vue
Labels: bug, 3. to review

#1277 fix faces issues
  src/views/FaceContent.vue
  src/views/Faces.vue
Labels: 3. to review

#1283 Migrate to nextcloud/ocp
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1282 Do not get all the files list when fetching the albums list
  lib/Album/AlbumMapper.php
  lib/Album/AlbumWithFiles.php
  lib/Sabre/Album/AlbumsHome.php
Labels: 3. to review, performances

#1284 Use composer requirements for psalm action
  .github/workflows/psalm.yml
Labels: 3. to review

#1300 Fix psalm errors
  lib/Album/AlbumMapper.php
  lib/Album/AlbumWithFiles.php
Labels: bug, 3. to review
