Repository nextcloud/photos, pull requests merged in 2022-11, with the labels that each got.

#1441 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1442 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1443 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1463 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1454 Remove broken icons.css references
  css/icons.scss
  lib/Controller/PageController.php
  lib/Controller/PublicAlbumController.php
Labels: 4. to release

#1480 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1481 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1482 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1484 Update screenshot in Readme.md
  screenshots/screenshot1.png
Labels: 3. to review

#1491 Prevent throwing an error in node deletion hook
  lib/Listener/CacheEntryRemovedListener.php
Labels: bug, 3. to review, backport-request

#1495 [stable25] Run npm audit fix
  package-lock.json
Labels: dependencies, 4. to release

#1494 [master] Run npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#1496 [stable24] Run npm audit fix
  js/photos-main.js
  js/photos-main.js.map
  js/photos-service-worker.js
  js/photos-src_assets_Illustrations_empty_svg.js.map
  js/photos-src_assets_Illustrations_folder_svg.js.map
  js/photos-src_assets_Illustrations_images_svg.js.map
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js.map
  js/photos-src_patchedRequest_js-node_modules_moment_locale_sync_recursive_-src_views_Timeline_vue.js
  js/photos-src_patchedRequest_js-node_modules_moment_locale_sync_recursive_-src_views_Timeline_vue.js.map
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_moment_locale_af_js-node_mod-100548.js
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_moment_locale_af_js-node_mod-100548.js.map
  js/photos-vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-208129.js
  js/photos-vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-208129.js.map
  js/photos-vendors-node_modules_webdav_dist_node_index_js-node_modules_webdav_dist_node_request_js.js
  js/photos-vendors-node_modules_webdav_dist_node_index_js-node_modules_webdav_dist_node_request_js.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1497 [stable23] Run npm audit fix
  js/photos-main.js
  js/photos-main.js.map
  js/photos-service-worker.js
  js/photos-src_assets_Illustrations_empty_svg.js.map
  js/photos-src_assets_Illustrations_folder_svg.js.map
  js/photos-src_assets_Illustrations_images_svg.js.map
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js.map
  js/photos-src_patchedRequest_js-node_modules_moment_locale_sync_recursive_-src_views_Timeline_vue.js
  js/photos-src_patchedRequest_js-node_modules_moment_locale_sync_recursive_-src_views_Timeline_vue.js.LICENSE.txt
  js/photos-src_patchedRequest_js-node_modules_moment_locale_sync_recursive_-src_views_Timeline_vue.js.map
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_moment_locale_af_js-node_mod-100548.js
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_moment_locale_af_js-node_mod-100548.js.LICENSE.txt
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_moment_locale_af_js-node_mod-100548.js.map
  js/photos-vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-701342.js
  js/photos-vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-701342.js.map
  js/photos-vendors-node_modules_webdav_dist_node_index_js-node_modules_webdav_dist_node_request_js.js
  js/photos-vendors-node_modules_webdav_dist_node_index_js-node_modules_webdav_dist_node_request_js.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1501 [stable25] Fix version20003Date20221102170153 migration
  lib/Migration/Version20003Date20221102170153.php
Labels: bug, high, 4. to release
