Repository nextcloud/photos, pull requests merged in 2022-10, with the labels that each got.

#1308 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1309 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1323 Fix e2e tests
  cypress/e2e/shared_albums.cy.js
  cypress/support/commands.js
  lib/Album/AlbumMapper.php
Labels: bug, 3. to review, backport-request

#1319 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1320 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1325 Make sure the default photos folder exists if none
  lib/Sabre/Album/AlbumRoot.php
  lib/Service/UserConfigService.php
Labels: bug, 3. to review, backport-request

#1340 This is Photos 2.0
  appinfo/info.xml
  package.json
Labels: 3. to review, backport-request

#1343 Photos 2.1.0 on 26
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1342 [stable25] This is Photos 2.0
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1361 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#1358 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#1359 Updating lint-stylelint.yml workflow from template
  .github/workflows/lint-stylelint.yml
Labels: dependencies

#1362 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#1363 Updating phpunit-sqlite.yml workflow from template
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies

#1364 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#1366 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1373 Change maintened branches in dependabot.yml
  .github/dependabot.yml
Labels: 3. to review

#1370 Limit auth backend to public albums
  lib/Listener/SabrePluginAuthInitListener.php
  lib/Sabre/PublicAlbumAuthBackend.php
Labels: bug, 3. to review

#1389 Fix logic of share album content fetching
  lib/Album/AlbumMapper.php
  lib/Controller/PreviewController.php
Labels: bug, 3. to review, backport-request

#1374 Make tag translations work by loading recognize translations
  lib/Controller/PageController.php
Labels: backport-request

#1367 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1401 [stable24] Bump workbox-webpack-plugin, qs, postcss, @nextcloud/moment and autoprefixed
  .github/workflows/static-analysis.yml
  composer.json
  composer.lock
  js/photos-main.js
  js/photos-main.js.map
  js/photos-service-worker.js
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_moment_locale_af_js-node_mod-100548.js
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_moment_locale_af_js-node_mod-100548.js.LICENSE.txt
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_moment_locale_af_js-node_mod-100548.js.map
  package-lock.json
  package.json
  psalm.xml
Labels: 3. to review, dependencies

#1413 [stable24] Update nextcloud/ocp dependency
  composer.json
Labels: 3. to review, dependencies

#1414 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1415 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
