Repository nextcloud/photos, pull requests merged in 2023-05, with the labels that each got.

#1337 Listen to more events for albums
  lib/Album/AlbumMapper.php
  lib/AppInfo/Application.php
  lib/Listener/AlbumsManagementEventListener.php
  lib/Listener/GroupDeletedListener.php
  lib/Listener/GroupUserRemovedListener.php
  lib/Listener/NodeDeletedListener.php
Labels: enhancement, 3. to review, backport-request, php, feature: albums

#1787 Add npm audit workflow
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review, backport-request, dependencies

#1823 fix: properly handle public link share deletion
  lib/Listener/AlbumsManagementEventListener.php
Labels: bug, 3. to review, backport-request, feature: albums

#1821 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1758 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
