Repository nextcloud/photos, pull requests merged in 2023-10, with the labels that each got.

#1952 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#2083 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2081 [stable24] Fix npm audit
  js/photos-main.js
  js/photos-main.js.map
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js.map
  js/photos-src_patchedRequest_js-node_modules_moment_locale_sync_recursive_-src_views_Timeline_vue.js
  js/photos-src_patchedRequest_js-node_modules_moment_locale_sync_recursive_-src_views_Timeline_vue.js.map
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  js/photos-vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-208129.js
  js/photos-vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-208129.js.map
  package-lock.json
Labels: 3. to review, dependencies

#2094 perf: make geoNameFolder lazy
  lib/Service/ReverseGeoCoderService.php
Labels: performances

#2103 Filter out some permission for public albums
  lib/Sabre/PropFindPlugin.php
Labels: bug, 3. to review, backport-request, php
