Repository nextcloud/photos, pull requests merged in 2023-12, with the labels that each got.

#2171 fix(DB): Fix "IS NOT NULL" database queries
  lib/DB/Place/PlaceMapper.php
Labels: bug, 3. to review, backport-request

#2092 [stable26] Update nextcloud/ocp dependency
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#2186 Catch and log error thrown while parsing dates from metadata
  lib/Listener/OriginalDateTimeMetadataProvider.php
Labels: 3. to review, backport-request

#2206 Fix TypeError with invalid coordinates (fix #2187)
  lib/Service/MediaPlaceManager.php
Labels: bug, 3. to review, backport-request
