Repository nextcloud/photos, pull requests merged in 2023-11, with the labels that each got.

#2119 init metadata
  lib/AppInfo/Application.php
Labels: bug, 2. developing

#2127 Add overlay on live photo
  lib/Sabre/PropFindPlugin.php
  src/components/File.vue
  src/services/DavRequest.js
  src/services/collectionFetcher.js
  src/services/fileFetcher.js
  src/store/files.js
Labels: enhancement, 3. to review, javascript

#2128 metadata: fix crash when datetime has invalid format
  lib/Listener/OriginalDateTimeMetadataProvider.php
Labels: bug, 3. to review

#2134 [stable24] enh: Add unique DOM identifiers for nav entries
  js/photos-main.js
  js/photos-main.js.map
  src/Photos.vue
Labels: 3. to review

#2130 Add sidebar to the build entries
  js/photos-node_modules_moment_locale_sync_recursive_-src_views_PhotosTab_vue.js
  js/photos-node_modules_moment_locale_sync_recursive_-src_views_PhotosTab_vue.js.map
  js/photos-sidebar.js
  js/photos-sidebar.js.LICENSE.txt
  js/photos-sidebar.js.map
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_leaflet-defaulticon-compatib-1c7d79.js
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_leaflet-defaulticon-compatib-1c7d79.js.LICENSE.txt
  js/photos-vendors-node_modules_nextcloud_moment_dist_index_js-node_modules_leaflet-defaulticon-compatib-1c7d79.js.map
  webpack.js
Labels: bug, 3. to review, javascript

#2135 Fix EXIF display conditions
  js/photos-node_modules_moment_locale_sync_recursive_-src_views_PhotosTab_vue.js
  js/photos-node_modules_moment_locale_sync_recursive_-src_views_PhotosTab_vue.js.map
  js/photos-sidebar.js
  js/photos-sidebar.js.map
  src/views/PhotosTab.vue
Labels: bug, 3. to review, javascript

#2141 Use NC URL to download cities list
  lib/Service/ReverseGeoCoderService.php
Labels: bug, 3. to review, php

#2142 Use information outline as sidebar icon
  js/photos-sidebar.js
  js/photos-sidebar.js.map
  src/sidebar.js
Labels: bug, 3. to review, javascript

#2100 [stable24] Fix npm audit
  js/photos-main.js
  js/photos-main.js.map
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js
  js/photos-src_mixins_GridConfig_js-src_utils_CancelableRequest_js-src_components_EmptyContent_vue-src_c-45f6cf.js.map
  js/photos-src_patchedRequest_js-node_modules_moment_locale_sync_recursive_-src_views_Timeline_vue.js
  js/photos-src_patchedRequest_js-node_modules_moment_locale_sync_recursive_-src_views_Timeline_vue.js.map
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js
  js/photos-src_patchedRequest_js-src_views_Tags_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  js/photos-vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-208129.js
  js/photos-vendors-node_modules_nextcloud_vue_dist_Components_ActionButton_js-node_modules_nextcloud_vue-208129.js.map
  js/photos-vendors-node_modules_webdav_dist_node_index_js-node_modules_webdav_dist_node_request_js.js
  js/photos-vendors-node_modules_webdav_dist_node_index_js-node_modules_webdav_dist_node_request_js.js.map
  package-lock.json
Labels: 3. to review, dependencies, feedback-requested
