Repository nextcloud/photos, pull requests merged in 2023-08, with the labels that each got.

#1958 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies, feedback-requested

#1938 [master] Fix npm audit
  js/photos-src_views_Faces_vue.js
  js/photos-src_views_Faces_vue.js.LICENSE.txt
  js/photos-src_views_Faces_vue.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1936 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2034 techdebt(DI): Use public IThrottler interface which exists since 25
  lib/Sabre/PublicRootCollection.php
  psalm.xml
Labels: 3. to review, technical debt
