Repository nextcloud/photos, pull requests merged in 2024-01, with the labels that each got.

#2244 Request background job to generate metadata on non-local files
  lib/AppInfo/Application.php
  lib/Listener/ExifMetadataProvider.php
  lib/Listener/OriginalDateTimeMetadataProvider.php
  lib/Listener/SizeMetadataProvider.php
Labels: enhancement, 3. to review, backport-request, php, performances

#2236 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2203 [stable28] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#2202 [master] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#2252 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2254 Update npm and node engines versions
  package.json
Labels: dependencies

#2264 fix(a11y): Fix heading hierarchy in some places
  js/photos-main.js
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-src_views_Places_vue.js
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-src_views_Places_vue.js.map
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-src_views_SharedAlbums_vue.js
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-src_views_SharedAlbums_vue.js.map
  js/photos-node_modules_vue-material-design-icons_PackageVariant_vue-node_modules_vue-material-design-ic-88a20b.js
  js/photos-node_modules_vue-material-design-icons_PackageVariant_vue-node_modules_vue-material-design-ic-88a20b.js.LICENSE.txt
  js/photos-node_modules_vue-material-design-icons_PackageVariant_vue-node_modules_vue-material-design-ic-88a20b.js.map
  js/photos-public.js
  js/photos-src_components_Faces_FaceCover_vue.js
  js/photos-src_components_Faces_FaceCover_vue.js.LICENSE.txt
  js/photos-src_components_Faces_FaceCover_vue.js.map
  js/photos-src_mixins_AbortControllerMixin_js-src_views_Faces_vue.js
  js/photos-src_mixins_AbortControllerMixin_js-src_views_Faces_vue.js.LICENSE.txt
  js/photos-src_mixins_AbortControllerMixin_js-src_views_Faces_vue.js.map
  js/photos-src_mixins_FetchFilesMixin_js-src_components_Faces_FaceMergeForm_vue.js
  js/photos-src_mixins_FetchFilesMixin_js-src_components_Faces_FaceMergeForm_vue.js.LICENSE.txt
  js/photos-src_mixins_FetchFilesMixin_js-src_components_Faces_FaceMergeForm_vue.js.map
  js/photos-src_views_Albums_vue.js
  js/photos-src_views_Albums_vue.js.map
  js/photos-src_views_FaceContent_vue.js
  js/photos-src_views_FaceContent_vue.js.LICENSE.txt
  js/photos-src_views_FaceContent_vue.js.map
  js/photos-src_views_Faces_vue.js
  js/photos-src_views_Faces_vue.js.LICENSE.txt
  js/photos-src_views_Faces_vue.js.map
  src/components/Faces/FaceCover.vue
  src/mixins/FaceCover.scss
  src/views/Albums.vue
  src/views/Places.vue
  src/views/SharedAlbums.vue
Labels: 3. to review, accessibility

#2280 Filter out large EXIF entries
  lib/Listener/ExifMetadataProvider.php
Labels: bug, 3. to review, php

#2205 Fix Fatal Error in Album setCollaborator function - redefining computeKey function
  lib/Album/AlbumMapper.php
Labels: feedback-requested

#2269 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
