Repository nextcloud/photos, pull requests merged in 2024-08, with the labels that each got.

#2571 fix(migrations): duplicated preference
  appinfo/info.xml
  lib/Migration/Version30000Date20240417075404.php
  lib/Migration/Version3000Date20240417075404.php
Labels: bug, 3. to review

#2596 fix: remove nextcloud_photos_ tmp files when done
  lib/Service/ReverseGeoCoderService.php
Labels: bug, 3. to review, backport-request

#2593 fix(migration): Fix migration for MySQL which does not allow joining
  .gitignore
  appinfo/info.xml
  composer.json
  lib/Migration/Version30000Date20240417075405.php
  tests/Album/AlbumMapperTest.php
  tests/Migration/Version30000Date20240417075405Test.php
  tests/bootstrap.php
  tests/phpunit.xml
Labels: 3. to review

#2619 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#2562 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2630 chore: Move Symfony console to dev deps
  composer.json
  composer.lock
Labels: 3. to review, dependencies, php

#2629 chore: Use composer-bin-plugin
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  lib/Album/AlbumMapper.php
  lib/Command/AlbumAddCommand.php
  lib/Command/AlbumCreateCommand.php
  lib/Controller/PageController.php
  lib/Listener/ExifMetadataProvider.php
  lib/Listener/OriginalDateTimeMetadataProvider.php
  lib/Migration/Version20000Date20220727125801.php
  lib/Migration/Version20001Date20220830131446.php
  lib/Migration/Version20003Date20221102170153.php
  lib/Sabre/Album/AlbumPhoto.php
  lib/Sabre/Album/AlbumRoot.php
  lib/Sabre/Album/PublicAlbumPhoto.php
  lib/Sabre/Album/PublicAlbumRoot.php
  lib/Sabre/Album/SharedAlbumRoot.php
  lib/Sabre/CollectionPhoto.php
  lib/Sabre/PhotosHome.php
  lib/Sabre/Place/PlacePhoto.php
  lib/Sabre/Place/PlaceRoot.php
  lib/Sabre/PublicAlbumAuthBackend.php
  lib/Sabre/PublicRootCollection.php
  lib/Service/MediaPlaceManager.php
  lib/Service/ReverseGeoCoderService.php
  psalm.xml
  tests/Album/AlbumMapperTest.php
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: 3. to review, dependencies, php
