Repository nextcloud/photos, pull requests merged in 2024-07, with the labels that each got.

#2465 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2488 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2462 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2510 chore(deps): Update nextcloud/coding-standard and nextcloud/ocp
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  composer.json
  composer.lock
  lib/Album/AlbumMapper.php
  lib/AppInfo/Application.php
  lib/Command/MapMediaToPlaceCommand.php
  lib/Controller/ApiController.php
  lib/Controller/PreviewController.php
  lib/Controller/PublicAlbumController.php
  lib/Controller/PublicPreviewController.php
  lib/Listener/AlbumsManagementEventListener.php
  lib/Listener/PlaceManagerEventListener.php
  lib/Listener/SabrePluginAuthInitListener.php
  lib/Listener/TagListener.php
  lib/Migration/Version20000Date20220727125801.php
  lib/Migration/Version20001Date20220830131446.php
  lib/Migration/Version20003Date20221102170153.php
  lib/Sabre/Album/AlbumPhoto.php
  lib/Sabre/Album/SharedAlbumRoot.php
  lib/Sabre/Album/SharedAlbumsHome.php
  lib/Sabre/CollectionPhoto.php
  lib/Sabre/PhotosHome.php
  lib/Sabre/Place/PlacePhoto.php
  lib/Sabre/Place/PlacesHome.php
  lib/Sabre/PropFindPlugin.php
  lib/Sabre/PublicRootCollection.php
  lib/Sabre/RootCollection.php
  lib/Service/ReverseGeoCoderService.php
  tests/psalm-baseline.xml
Labels: 3. to review, dependencies, php

#2467 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2519 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#2524 fix: avoid erroring out on corrupt image data
  lib/Listener/SizeMetadataProvider.php
Labels: bug, 3. to review, backport-request

#2533 feat: Handle complex location type
  lib/Sabre/PropFindPlugin.php
Labels: backport-request

#2464 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2473 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2549 chore: update workflows from templates
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#2550 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2551 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2526 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2525 [stable27] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies
