Repository nextcloud/photos, pull requests merged in 2024-04, with the labels that each got.

#2425 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2424 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2430 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2404 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2434 Check download attribute when fetching previews
  lib/Controller/PreviewController.php
  tests/psalm-baseline.xml
Labels: enhancement, 3. to review, backport-request, php

#2441 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2419 [stable29] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2448 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#2449 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#2455 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2423 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2456 Add block-merge-eol workflow
  .github/workflows/block-merge-eol.yml
Labels: 4. to release
