Repository nextcloud/photos, pull requests merged in 2024-03, with the labels that each got.

#2374 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2375 Use blurhash as preview
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_ArrowLeft_vue--996eaf.js
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_ArrowLeft_vue--996eaf.js.LICENSE.txt
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_ArrowLeft_vue--996eaf.js.map
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_ArrowLeft_vue--f24de2.js
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_ArrowLeft_vue--f24de2.js.LICENSE.txt
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_ArrowLeft_vue--f24de2.js.map
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_PackageVariant-6bf9ec.js
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_PackageVariant-6bf9ec.js.LICENSE.txt
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_PackageVariant-6bf9ec.js.map
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_PackageVariant-bff37a.js
  js/photos-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_PackageVariant-bff37a.js.map
  js/photos-node_modules_vue-material-design-icons_AlertCircle_vue-node_modules_vue-material-design-icons-9eee11.js
  js/photos-node_modules_vue-material-design-icons_AlertCircle_vue-node_modules_vue-material-design-icons-9eee11.js.LICENSE.txt
  js/photos-node_modules_vue-material-design-icons_AlertCircle_vue-node_modules_vue-material-design-icons-9eee11.js.map
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-node_modules_vue-material-design-icons_P-3c3243.js
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-node_modules_vue-material-design-icons_P-3c3243.js.LICENSE.txt
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-node_modules_vue-material-design-icons_P-3c3243.js.map
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-node_modules_vue-material-design-icons_P-e1736f.js
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-node_modules_vue-material-design-icons_P-e1736f.js.LICENSE.txt
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-node_modules_vue-material-design-icons_P-e1736f.js.map
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-src_views_Timeline_vue.js
  js/photos-node_modules_vue-material-design-icons_ArrowLeft_vue-src_views_Timeline_vue.js.map
  js/photos-node_modules_vue-material-design-icons_FolderMultipleImage_vue-src_views_AlbumContent_vue.js
  js/photos-node_modules_vue-material-design-icons_FolderMultipleImage_vue-src_views_AlbumContent_vue.js.map
  js/photos-node_modules_vue-material-design-icons_PackageVariant_vue-node_modules_vue-material-design-ic-88a20b.js
  js/photos-node_modules_vue-material-design-icons_PackageVariant_vue-node_modules_vue-material-design-ic-88a20b.js.LICENSE.txt
  js/photos-node_modules_vue-material-design-icons_PackageVariant_vue-node_modules_vue-material-design-ic-88a20b.js.map
  js/photos-node_modules_vue-material-design-icons_PackageVariant_vue-node_modules_vue-material-design-ic-934ab5.js
  js/photos-node_modules_vue-material-design-icons_PackageVariant_vue-node_modules_vue-material-design-ic-934ab5.js.map
  js/photos-src_components_Collection_CollectionContent_vue-src_components_PhotosPicker_vue.js
  js/photos-src_components_Collection_CollectionContent_vue-src_components_PhotosPicker_vue.js.map
  js/photos-src_mixins_AbortControllerMixin_js-src_mixins_FilesSelectionMixin_js-src_components_File_vue--80ca54.js
  js/photos-src_mixins_AbortControllerMixin_js-src_mixins_FilesSelectionMixin_js-src_components_File_vue--80ca54.js.LICENSE.txt
  js/photos-src_mixins_AbortControllerMixin_js-src_mixins_FilesSelectionMixin_js-src_components_File_vue--80ca54.js.map
  js/photos-src_views_AlbumContent_vue.js
  js/photos-src_views_AlbumContent_vue.js.map
  js/photos-src_views_FaceContent_vue.js
  js/photos-src_views_FaceContent_vue.js.map
  js/photos-src_views_SharedAlbumContent_vue.js
  js/photos-src_views_SharedAlbumContent_vue.js.LICENSE.txt
  js/photos-src_views_SharedAlbumContent_vue.js.map
  js/photos-vendors-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_Accoun-ac76f8.js
  js/photos-vendors-node_modules_blurhash_dist_esm_index_js-node_modules_vue-material-design-icons_Accoun-ac76f8.js.map
  js/photos-vendors-node_modules_nextcloud_sharing_dist_index_js-node_modules_blurhash_dist_esm_index_js--bc3bd7.js
  js/photos-vendors-node_modules_nextcloud_sharing_dist_index_js-node_modules_blurhash_dist_esm_index_js--bc3bd7.js.map
  js/photos-vendors-node_modules_nextcloud_sharing_dist_index_js-node_modules_blurhash_dist_esm_index_js--cf3d5b.js
  js/photos-vendors-node_modules_nextcloud_sharing_dist_index_js-node_modules_blurhash_dist_esm_index_js--cf3d5b.js.map
  js/photos-vendors-node_modules_nextcloud_sharing_dist_index_js-node_modules_debounce_index_js-node_modu-b3de47.js
  js/photos-vendors-node_modules_nextcloud_sharing_dist_index_js-node_modules_debounce_index_js-node_modu-b3de47.js.map
  js/photos-vendors-node_modules_vue-material-design-icons_AccountBoxMultipleOutline_vue-node_modules_vue-7c36ca.js
  js/photos-vendors-node_modules_vue-material-design-icons_AccountBoxMultipleOutline_vue-node_modules_vue-7c36ca.js.map
  package-lock.json
  package.json
  src/components/File.vue
  src/services/DavRequest.js
  src/services/PreviewService.js
Labels: 3. to review, javascript, performances

#2379 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2380 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2392 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2391 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2389 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2388 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2387 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2383 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#2386 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2393 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2390 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2316 chore: update workflows from templates
  .github/workflows/block-merge-freeze.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated, feedback-requested

#2403 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2417 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2406 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#2418 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies
