Repository nextcloud/photos, pull requests merged in 2024-12, with the labels that each got.

#2736 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#2564 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2563 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 4. to release

#2741 [stable30] chore: update composer lock and nextcloud/ocp
  appinfo/routes.php
  composer.json
  composer.lock
  lib/Dashboard/OnThisDay.php
  lib/Listener/AlbumsManagementEventListener.php
  lib/Listener/TagListener.php
  lib/Sabre/PublicAlbumAuthBackend.php
  tests/bootstrap.php
Labels: dependencies
