Repository nextcloud/photos, pull requests merged in 2025-09, with the labels that each got.

#3148 fix(AutomaticPlaceMapperJob): Do not fail when there are no users
  lib/Jobs/AutomaticPlaceMapperJob.php
Labels: bug, 3. to review

#3145 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3178 chore(deps): Add missing resolved and integrity fields in package-lock.json
  package-lock.json
Labels: 3. to review, backport-request, dependencies

#3182 [stable31] fix(deps): Use vue-loader ^15.11.1 for Vue 2
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#3191 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
