Repository nextcloud/photos, pull requests merged in 2025-05, with the labels that each got.

#2997 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2996 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3012 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3013 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3019 chore: Remove psalm-baseline.xml and correct issues
  composer.json
  lib/Controller/AlbumsController.php
  lib/Controller/PreviewController.php
  lib/Jobs/AutomaticPlaceMapperJob.php
  lib/Listener/ExifMetadataProvider.php
  lib/Listener/OriginalDateTimeMetadataProvider.php
  lib/Listener/SabrePluginAuthInitListener.php
  lib/Listener/SizeMetadataProvider.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: 3. to review, php

#3018 chore: Apply rector php8.1 set
  composer.json
  lib/Album/AlbumFile.php
  lib/Album/AlbumInfo.php
  lib/Album/AlbumMapper.php
  lib/Album/AlbumWithFiles.php
  lib/Command/AlbumAddCommand.php
  lib/Command/AlbumCreateCommand.php
  lib/Command/UpdateReverseGeocodingFilesCommand.php
  lib/Controller/AlbumsController.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Controller/PreviewController.php
  lib/Controller/PublicAlbumController.php
  lib/DB/PhotosFile.php
  lib/DB/Place/PlaceFile.php
  lib/DB/Place/PlaceInfo.php
  lib/DB/Place/PlaceMapper.php
  lib/Dashboard/OnThisDay.php
  lib/Jobs/AutomaticPlaceMapperJob.php
  lib/Listener/AlbumsManagementEventListener.php
  lib/Listener/ExifMetadataProvider.php
  lib/Listener/LoadSidebarScripts.php
  lib/Listener/OriginalDateTimeMetadataProvider.php
  lib/Listener/PlaceMetadataProvider.php
  lib/Listener/SabrePluginAuthInitListener.php
  lib/Listener/SizeMetadataProvider.php
  lib/Listener/TagListener.php
  lib/Migration/Version30000Date20240417075405.php
  lib/RepairStep/InitMetadata.php
  lib/Sabre/Album/AlbumPhoto.php
  lib/Sabre/Album/AlbumRoot.php
  lib/Sabre/Album/AlbumsHome.php
  lib/Sabre/Album/PublicAlbumPhoto.php
  lib/Sabre/Album/PublicAlbumRoot.php
  lib/Sabre/Album/SharedAlbumRoot.php
  lib/Sabre/Album/SharedAlbumsHome.php
  lib/Sabre/CollectionPhoto.php
  lib/Sabre/PhotosHome.php
  lib/Sabre/Place/PlacePhoto.php
  lib/Sabre/Place/PlaceRoot.php
  lib/Sabre/Place/PlacesHome.php
  lib/Sabre/PropFindPlugin.php
  lib/Sabre/PublicRootCollection.php
  lib/Sabre/RootCollection.php
  lib/Service/MediaPlaceManager.php
  lib/Service/ReverseGeoCoderService.php
  lib/Service/UserConfigService.php
  rector.php
  tests/Album/AlbumMapperTest.php
  tests/Migration/Version30000Date20240417075405Test.php
  tests/bootstrap.php
  vendor-bin/rector/composer.json
  vendor-bin/rector/composer.lock
Labels: 3. to review, php

#3029 chore(tests): Cleanup bootstrap.php to be forward-compatible
  tests/bootstrap.php
Labels: 3. to review

#3039 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3021 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#3038 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
