Repository nextcloud/photos, pull requests merged in 2025-04, with the labels that each got.

#2918 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2919 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2929 [stable31] test: Fix test and add CI job
  .github/workflows/node-test.yml
  package-lock.json
  package.json
  src/services/TiledLayout.spec.js
Labels: 3. to review, backport-request, javascript

#2938 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2917 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2947 chore: update workflows from organization
  .github/workflows/cypress.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#2948 ci: drop stable29 from dependabot and include `vendor-bin`
  .github/dependabot.yml
Labels: 3. to review

#2980 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2979 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2981 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2966 fix(Places): Use event metadata to compute the place
  lib/DB/Place/PlaceMapper.php
  lib/Listener/PlaceMetadataProvider.php
  lib/Service/MediaPlaceManager.php
Labels: bug, 3. to review, backport-request, php
